# The base box is on centos6 X86_64

Vagrant.configure(2) do |config|

  config.vm.box = "base"

  config.vm.provider "virtualbox" do |v|
    v.memory = "380"
    v.cpus = "2"
  end

  config.vm.define :ansible do |a1|
    a1.vm.hostname = "ansible"
    a1.vm.network :private_network, ip: "10.10.1.254"
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    a1.vm.provision "shell", inline: <<-SHELL
      sudo yum install ansible -y
    SHELL
  end

  config.vm.define :w1 do |w1|
    w1.vm.hostname = "www-1"
    w1.vm.network :private_network, ip: "10.10.1.2"
    # config.vm.network "forwarded_port", guest: 80, host: 8080
  end
  config.vm.define :w2 do |w2|
    w2.vm.hostname = "www-2"
    w2.vm.network :private_network, ip: "10.10.1.3"
    # config.vm.network "forwarded_port", guest: 80, host: 8080
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    sudo rm /etc/localtime
    sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
  SHELL
end
